blank_issues_enabled: false
contact_links:
  - name: Discord Channel for Rainbird (homebridge-rainbird)
    url: https://discord.gg/peABghgtaV
    about: Please ask and answer questions here.
  - name: Rainbrid - Pull Requests
    url: https://github.com/donavanbecker/rainbird/pulls
    about: Please report security vulnerabilities here.
