name: Support Request
description: Need help?
title: "Support Request: "
labels: [question]
assignees:
  - donavanbecker
  - mantorok1
body:
  - type: markdown
    attributes:
      value: |
        You must use the issue template below when submitting a support request.
  - type: input
    attributes:
      label: Describe Your Problem
      placeholder: A clear and concise description of what problem you are trying to solve.
    validations:
      required: true
  - type: textarea
    id: Logs
    attributes:
      label: Relevant log output
      placeholder: Bug reports that do not contain logs may be closed without warning. Show the RainBird logs here. Remove any sensitive information. Please Turn on Debug Mode before submitting your Issue so more logs can be shared to fix the issue being submitted.
      render: shell
    validations:
      required: false
  - type: textarea
    id: Config
    attributes:
      label: Config for RainBird
      placeholder: Paste your RainBird config here. Remove any sensitive information, such as your device ipaddress or device password.
      render: shell
    validations:
      required: false
  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable add screenshots to help explain your problem.
      placeholder: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: input
    attributes:
      label: Device & Model
      placeholder: If applicable, add screenshots to help explain your problem.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Environment
  - type: input
    attributes:
      label: Node.js Version
      placeholder: v18.0.0
    validations:
      required: true
  - type: input
    attributes:
      label: Rainbird Version
      placeholder: v0.1.0
    validations:
      required: true
  - type: input
    attributes:
      label: Operating System
      placeholder: Raspbian / Ubuntu / Debian / Windows / macOS / Docker
    validations:
      required: true
